# Ryan Ravikumar - 9/10/2026 - Analytics for FinSight

## Data Cleaning Process

In [6]:
%pip install pandas numpy scipy

Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.6)
Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\python\pythoncore-3.14-64\lib\site-packages (2.5.3)
Requirement already satisfied: scipy in c:\users\lenovo\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.18.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [7]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [17]:
import pandas as pd
import numpy as np
from scipy import stats

raw = pd.read_excel("initial_data/FinSight_Dataset.xlsx")
df = raw.copy()
print(df.shape)
df.head()

(508, 44)

,Customer_ID,Full_Name,NIC_Number,Gender,Date_of_Birth,Age,District,Province,Urban_Rural,Customer_Segment,...,PEP_Flag,Has_Fixed_Deposit,FD_Amount,Has_Insurance,Has_Mobile_Wallet,Number_of_Products,Acquisition_Channel,Referral_Source,Last_Campaign_Response,Promo_Code_Used
0,FSL-0001,Mark Johnson,808614657V,Female,1980-12-26,43,Kandy,Central,Suburban,Regular,...,No,No,NaN,No,Yes,2,Referral,Friend,Responded,Yes
1,FSL-0002,Deborah Phillips,718478527V,Female,1971-12-13,52,Badulla,Uva,Urban,Starter,...,No,No,NaN,No,Yes,2,Referral,Family,Ignored,No
2,FSL-0003,Charles Phillips,933515010V,Male,1993-12-17,30,Kandy,Central,Suburban,Regular,...,No,Yes,1166599.45,No,No,3,Agent,Colleague,Responded,No
3,FSL-0004,Rachel Hall,720422796V,Male,1972-02-11,51,Kandy,Central,Suburban,Regular,...,No,Yes,1051113.61,Yes,No,4,Referral,NaN,Ignored,Yes
4,FSL-0005,Sharon Bell,940729689V,Male,1994-03-13,29,Colombo,Western,Suburban,Regular,...,No,No,NaN,No,Yes,3,Referral,NaN,Unsubscribed,No

Data inspection

In [16]:
df.info()
df.describe().T

<class 'pandas.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 44 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer_ID                508 non-null    str
 1   Full_Name                  500 non-null    str
 2   NIC_Number                 508 non-null    str
 3   Gender                     508 non-null    str
 4   Date_of_Birth              508 non-null    datetime64[us]
 5   Age                        508 non-null    int64
 6   District                   503 non-null    str
 7   Province                   508 non-null    str
 8   Urban_Rural                508 non-null    str
 9   Customer_Segment           503 non-null    str
 10  Account_Open_Date          508 non-null    datetime64[us]
 11  Customer_Tenure_Years      508 non-null    float64
 12  Savings_Balance            502 non-null    float64
 13  Monthly_Deposit_Avg        502 non-null    float64
 14  Monthly_Withdrawal_Avg     508 non-null    float64
 15  Net_Monthly_Flow           508 non-null    float64
 16  Account_Status             508 non-null    str
 17  Interest_Rate_Tier         508 non-null    str
 18  Has_Loan                   503 non-null    str
 19  Loan_Type                  218 non-null    str
 20  Loan_Amount                217 non-null    float64
 21  Loan_Tenure_Months         218 non-null    float64
 22  Monthly_Repayment_Amount   218 non-null    float64
 23  Loan_Repayment_Status      220 non-null    str
 24  Loan_Start_Date            220 non-null    datetime64[us]
 25  Outstanding_Loan_Balance   219 non-null    float64
 26  Mobile_App_User            508 non-null    str
 27  Last_Login_Date            339 non-null    datetime64[us]
 28  Monthly_Transaction_Count  508 non-null    int64
 29  Preferred_Channel          508 non-null    str
 30  Push_Notification_Enabled  508 non-null    str
 31  KYC_Status                 501 non-null    str
 32  KYC_Last_Updated           508 non-null    datetime64[us]
 33  Suspicious_Activity_Flag   508 non-null    str
 34  PEP_Flag                   508 non-null    str
 35  Has_Fixed_Deposit          508 non-null    str
 36  FD_Amount                  150 non-null    float64
 37  Has_Insurance              508 non-null    str
 38  Has_Mobile_Wallet          508 non-null    str
 39  Number_of_Products         508 non-null    int64
 40  Acquisition_Channel        508 non-null    str
 41  Referral_Source            256 non-null    str
 42  Last_Campaign_Response     508 non-null    str
 43  Promo_Code_Used            508 non-null    str
dtypes: datetime64[us](5), float64(10), int64(3), str(26)
memory usage: 174.8 KB

,count,mean,min,25%,50%,75%,max,std
Date_of_Birth,508,1986-11-01 10:37:47.716535,1890-03-11 00:00:00,1978-06-15 18:00:00,1987-01-15 12:00:00,1995-06-16 00:00:00,2020-05-01 00:00:00,NaN
Age,508.0,37.005906,4.0,28.0,36.5,45.0,150.0,12.132973
Account_Open_Date,508,2019-07-29 12:42:31.181102,2015-01-14 00:00:00,2017-02-04 18:00:00,2019-09-05 00:00:00,2021-10-21 18:00:00,2026-06-01 00:00:00,NaN
Customer_Tenure_Years,508.0,4.450394,0.0,2.2,4.3,6.9,9.0,2.635717
Savings_Balance,502.0,2751255.695717,-88000.0,120697.155,442763.82,729013.3525,999999999.0,44611330.086692
Monthly_Deposit_Avg,502.0,37871.756454,194.79,5607.16,17694.735,39642.0225,347140.12,57934.118045
Monthly_Withdrawal_Avg,508.0,59007.534528,100.99,3230.255,9684.8,22889.24,9999999.0,592686.17979
Net_Monthly_Flow,508.0,15896.003681,30.87,1850.815,5851.795,16963.655,196240.99,26785.955644
Loan_Amount,217.0,1427319.142258,54308.53,708817.38,1421377.63,2114078.24,2998363.15,847290.637522
Loan_Tenure_Months,218.0,34.12844,12.0,12.0,36.0,48.0,60.0,17.48474
Monthly_Repayment_Amount,218.0,66446.899312,1008.14,20592.45,47278.575,82529.8625,274849.53,64127.945546
Loan_Start_Date,220,2021-09-13 16:34:54.545454,2008-03-20 00:00:00,2020-08-01 00:00:00,2022-06-26 00:00:00,2023-06-03 00:00:00,2023-12-31 00:00:00,NaN
Outstanding_Loan_Balance,219.0,767147.827534,16258.84,230947.3,669510.68,1189684.88,2460698.36,591850.618201
Last_Login_Date,339,2023-09-28 12:19:06.902654,2023-06-01 00:00:00,2023-08-02 00:00:00,2023-09-21 00:00:00,2023-11-11 00:00:00,2027-01-01 00:00:00,NaN
Monthly_Transaction_Count,508.0,12.844488,0.0,3.0,10.0,22.0,35.0,10.856125
KYC_Last_Updated,508,2022-01-23 04:46:17.952756,2020-01-07 00:00:00,2021-01-29 18:00:00,2021-12-25 00:00:00,2023-02-25 18:00:00,2024-01-01 00:00:00,NaN
FD_Amount,150.0,1072150.227467,113217.78,612684.6025,1094276.635,1500870.8425,1977885.84,534963.305598
Number_of_Products,508.0,2.501969,1.0,2.0,2.0,3.0,6.0,0.941062

**Concerns**
Minimum and maximum of "Age" indicates ages of 4 and 150, needs further investigating.

In [18]:
df.loc[df["Age"]==4].T

                                            33
Customer_ID                           FSL-0034
Full_Name                          Susan Jones
NIC_Number                          961124538V
Gender                                    Male
Date_of_Birth              2020-05-01 00:00:00
Age                                          4
District                                 Galle
Province                              Southern
Urban_Rural                              Urban
Customer_Segment                       Premium
Account_Open_Date          2021-09-07 00:00:00
Customer_Tenure_Years                      2.3
Savings_Balance                      512759.98
Monthly_Deposit_Avg                   36664.58
Monthly_Withdrawal_Avg                14182.33
Net_Monthly_Flow                      22482.25
Account_Status                          Active
Interest_Rate_Tier                      Silver
Has_Loan                                   Yes
Loan_Type                              Housing
Loan_Amount                          374282.73
Loan_Tenure_Months                        12.0
Monthly_Repayment_Amount              34309.25
Loan_Repayment_Status                  On-Time
Loan_Start_Date            2022-09-08 00:00:00
Outstanding_Loan_Balance             288754.25
Mobile_App_User                            Yes
Last_Login_Date            2023-08-22 00:00:00
Monthly_Transaction_Count                    3
Preferred_Channel                       Branch
Push_Notification_Enabled                  Yes
KYC_Status                            Verified
KYC_Last_Updated           2022-05-12 00:00:00
Suspicious_Activity_Flag                    No
PEP_Flag                                    No
Has_Fixed_Deposit                           No
FD_Amount                                  NaN
Has_Insurance                               No
Has_Mobile_Wallet                           No
Number_of_Products                           2
Acquisition_Channel                    Digital
Referral_Source                            NaN
Last_Campaign_Response                 Ignored
Promo_Code_Used                             No

While there is no explicit rule to handle the minimum "Age" value (4), the following evidence suggests handling is necessary:
1. The "Mobile_App_User" is set to "Yes", which isn't possible given age.
2. The "Account_Open_Date" value indicates that the user was a year old upon account creation.
3. The "NIC_Number" contains a value, this is not possible for a four year old to obtain.

In [24]:
df.loc[(df["Age"]-4).abs().sort_values().index[:5]].T

,33,319,467,77,273
Customer_ID,FSL-0034,FSL-0320,FSL-0468,FSL-0078,FSL-0274
Full_Name,Susan Jones,Samantha Moore,Rachel Allen,Lisa Thompson,Amanda Anderson
NIC_Number,961124538V,027878908V,026797630V,020317932V,023164687V
Gender,Male,Female,Female,Male,Male
Date_of_Birth,2020-05-01 00:00:00,2002-10-14 00:00:00,2002-06-28 00:00:00,2002-01-31 00:00:00,2002-11-12 00:00:00
Age,4,21,21,21,21
District,Galle,Galle,Colombo,Kurunegala,Colombo
Province,Southern,Southern,Western,North Western,Western
Urban_Rural,Urban,Urban,Rural,Urban,Rural
Customer_Segment,Premium,Regular,Regular,Starter,Regular
Account_Open_Date,2021-09-07 00:00:00,2022-12-23 00:00:00,2017-11-21 00:00:00,2020-05-16 00:00:00,2020-06-19 00:00:00
Customer_Tenure_Years,2.3,1.0,6.1,3.6,3.5
Savings_Balance,512759.98,84579.53,103067.51,89425.38,587368.46
Monthly_Deposit_Avg,36664.58,4525.93,2976.42,4655.67,22288.35
Monthly_Withdrawal_Avg,14182.33,3728.11,1292.29,3976.4,17585.67
Net_Monthly_Flow,22482.25,797.82,1684.13,679.27,4702.68
Account_Status,Active,Active,Inactive,Inactive,Inactive
Interest_Rate_Tier,Silver,Standard,Standard,Standard,Silver
Has_Loan,Yes,No,No,Yes,Yes
Loan_Type,Housing,NaN,NaN,Personal,Personal
Loan_Amount,374282.73,NaN,NaN,2382626.71,1666431.58
Loan_Tenure_Months,12.0,NaN,NaN,36.0,36.0
Monthly_Repayment_Amount,34309.25,NaN,NaN,72802.48,50918.74
Loan_Repayment_Status,On-Time,NaN,NaN,Delayed,On-Time
Loan_Start_Date,2022-09-08 00:00:00,NaT,NaT,2023-05-20 00:00:00,2023-02-13 00:00:00
Outstanding_Loan_Balance,288754.25,NaN,NaN,1440886.24,1569390.53
Mobile_App_User,Yes,Yes,Yes,No,No
Last_Login_Date,2023-08-22 00:00:00,2023-06-20 00:00:00,2023-07-10 00:00:00,NaT,NaT
Monthly_Transaction_Count,3,6,8,0,3
Preferred_Channel,Branch,Agent,Online,Branch,App
Push_Notification_Enabled,Yes,Yes,Yes,No,Yes
KYC_Status,Verified,Verified,Verified,Verified,Verified
KYC_Last_Updated,2022-05-12 00:00:00,2021-03-18 00:00:00,2023-03-06 00:00:00,2023-08-18 00:00:00,2023-11-27 00:00:00
Suspicious_Activity_Flag,No,No,No,No,No
PEP_Flag,No,No,No,No,No
Has_Fixed_Deposit,No,No,Yes,No,No
FD_Amount,NaN,NaN,1014229.98,NaN,NaN
Has_Insurance,No,No,No,No,Yes
Has_Mobile_Wallet,No,No,Yes,No,Yes
Number_of_Products,2,1,3,2,4
Acquisition_Channel,Digital,Referral,Referral,Referral,Digital
Referral_Source,NaN,Colleague,Friend,NaN,NaN
Last_Campaign_Response,Ignored,Ignored,Ignored,Responded,Ignored
Promo_Code_Used,No,No,No,Yes,No

4. The above data indicates that the closest value to the minimum of "Age" is 21, which makes it more likely to be a typo.

In [25]:
df.loc[df["Age"]==150].T

                                           270
Customer_ID                           FSL-0271
Full_Name                          Gary Taylor
NIC_Number                          755708899V
Gender                                  Female
Date_of_Birth              1975-03-11 00:00:00
Age                                        150
District                               Badulla
Province                                   Uva
Urban_Rural                              Urban
Customer_Segment                       Regular
Account_Open_Date          2023-06-13 00:00:00
Customer_Tenure_Years                      0.6
Savings_Balance                      756483.71
Monthly_Deposit_Avg                   46897.86
Monthly_Withdrawal_Avg                17037.14
Net_Monthly_Flow                      29860.72
Account_Status                       Suspended
Interest_Rate_Tier                      Silver
Has_Loan                                   Yes
Loan_Type                              Vehicle
Loan_Amount                         2712813.13
Loan_Tenure_Months                        36.0
Monthly_Repayment_Amount              82891.51
Loan_Repayment_Status                  On-Time
Loan_Start_Date            2023-08-17 00:00:00
Outstanding_Loan_Balance             1806849.6
Mobile_App_User                             No
Last_Login_Date                            NaT
Monthly_Transaction_Count                    5
Preferred_Channel                          App
Push_Notification_Enabled                   No
KYC_Status                             Expired
KYC_Last_Updated           2023-07-21 00:00:00
Suspicious_Activity_Flag                    No
PEP_Flag                                    No
Has_Fixed_Deposit                           No
FD_Amount                                  NaN
Has_Insurance                               No
Has_Mobile_Wallet                           No
Number_of_Products                           2
Acquisition_Channel                    Digital
Referral_Source                            NaN
Last_Campaign_Response                 Ignored
Promo_Code_Used                             No

An investigation of the maximum reveals the following:
1. A contradication between "Age" (150) and the "Date_of_Birth" (1975-03-11).

In [28]:
df.isna().sum()

Customer_ID                    0
Full_Name                      8
NIC_Number                     0
Gender                         0
Date_of_Birth                  0
Age                            0
District                       5
Province                       0
Urban_Rural                    0
Customer_Segment               5
Account_Open_Date              0
Customer_Tenure_Years          0
Savings_Balance                6
Monthly_Deposit_Avg            6
Monthly_Withdrawal_Avg         0
Net_Monthly_Flow               0
Account_Status                 0
Interest_Rate_Tier             0
Has_Loan                       5
Loan_Type                    290
Loan_Amount                  291
Loan_Tenure_Months           290
Monthly_Repayment_Amount     290
Loan_Repayment_Status        288
Loan_Start_Date              288
Outstanding_Loan_Balance     289
Mobile_App_User                0
Last_Login_Date              169
Monthly_Transaction_Count      0
Preferred_Channel              0
Push_Notification_Enabled      0
KYC_Status                     7
KYC_Last_Updated               0
Suspicious_Activity_Flag       0
PEP_Flag                       0
Has_Fixed_Deposit              0
FD_Amount                    358
Has_Insurance                  0
Has_Mobile_Wallet              0
Number_of_Products             0
Acquisition_Channel            0
Referral_Source              252
Last_Campaign_Response         0
Promo_Code_Used                0
dtype: int64

Concerns over missing "FD_Amount", can be addressed if "Has_Fixed_Deposit" where the sumation of value "No" aligns with missing values in "FD_Amount."

In [29]:
df["Has_Fixed_Deposit"].value_counts(dropna=False)

Has_Fixed_Deposit
No     358
Yes    150
Name: count, dtype: int64

This confirms previous assumption where both "No" and missing values in "FD_Amount" is 358.

The "Has_loan" and "Loan_Type" columns also need to be investigated.

In [37]:
pd.crosstab(df["Has_Loan"].fillna("Missing"), df["Loan_Type"].isna(), rownames=["Has Loan"], 
            colnames=["Loan Type Missing"], margins=True)

Loan Type Missing  False  True  All
Has Loan
Missing                1     4    5
No                     1   284  285
Yes                  216     2  218
All                  218   290  508

The results point to the following concerns:
1. The 5 customers that have missing "Has_Loan" values, 4 have missing "Loan_Type" values but 1 has a "Loan_type" value recorded.
2. One customer that was marked as "No" contains a "Loan_Type."
3. 2 customers that marked "Yes" contain missing "Loan_Type."

In [38]:
cols_to_check=["Gender", "District", "Account_Status", "Customer_Segment", "Has_Loan"]

for col in cols_to_check:
    print(df[col].value_counts(dropna=False), "\n")

print("Duplicated (Identical): ", df.duplicated().sum())
print("Duplicated primay key (Customer_ID): ", df["Customer_ID"].duplicated().sum())
df.tail(10)

Gender
Female    261
Male      241
M           1
male        1
FEMALE      1
F           1
MALE        1
f           1
Name: count, dtype: int64

District
Jaffna         58
Kurunegala     56
Ratnapura      56
Gampaha        54
Badulla        50
Trincomalee    50
Colombo        49
Kandy          46
Matara         46
Galle          34
NaN             5
Columbo         1
Kanady          1
Gale            1
Jafna           1
Name: count, dtype: int64

Account_Status
Active       382
Inactive      80
Suspended     42
active         1
INACTIVE       1
suspended      1
Active         1
Name: count, dtype: int64

Customer_Segment
Regular    319
Starter     93
Premium     91
NaN          5
Name: count, dtype: int64

Has_Loan
No     285
Yes    218
NaN      5
Name: count, dtype: int64

Duplicated (Identical):  3
Duplicated primay key (Customer_ID):  8

,Customer_ID,Full_Name,NIC_Number,Gender,Date_of_Birth,Age,District,Province,Urban_Rural,Customer_Segment,...,PEP_Flag,Has_Fixed_Deposit,FD_Amount,Has_Insurance,Has_Mobile_Wallet,Number_of_Products,Acquisition_Channel,Referral_Source,Last_Campaign_Response,Promo_Code_Used
498,FSL-0499,Michael Johnson,850037799V,Male,1985-01-03,39,Gampaha,Western,Suburban,Starter,...,No,No,NaN,Yes,Yes,3,Referral,NaN,Responded,Yes
499,FSL-0500,Janet Parker,748239834V,Female,1974-11-19,49,Matara,Southern,Urban,Regular,...,No,Yes,1087392.46,No,No,3,Referral,NaN,Responded,No
500,FSL-0011,Joshua Mitchell,862063426V,Male,1986-07-25,37,Kurunegala,North Western,Urban,Regular,...,No,No,NaN,Yes,No,2,Referral,NaN,Ignored,No
501,FSL-0046,Nicole Morris,012378685V,Male,2001-08-25,22,Ratnapura,Sabaragamuwa,Suburban,Starter,...,No,Yes,1819779.08,No,Yes,3,Branch,NaN,Responded,No
502,FSL-0089,Catherine Mitchell,821642369V,Male,1982-06-13,41,Matara,Southern,Urban,Starter,...,No,Yes,1365551.20,No,Yes,3,Digital,NaN,Responded,Yes
503,FSL-0131,Ryan Torres,992664913V,Male,1999-09-23,24,Trincomalee,Eastern,Suburban,Regular,...,No,Yes,492870.74,No,Yes,3,Agent,NaN,Unsubscribed,Yes
504,FSL-0201,Nancy Johnson,821599078V,Male,1982-06-08,41,Gampaha,Western,Suburban,Regular,...,No,No,NaN,Yes,Yes,3,Referral,Friend,Responded,No
505,FSL-0281,Linda Scott,916433090V,Female,1991-05-23,32,Matara,Southern,Urban,Regular,...,No,Yes,912753.66,No,No,2,Branch,Colleague,Ignored,Yes
506,FSL-0351,Charles Morgan,717648100V,Female,1971-09-21,52,Gampaha,Western,Rural,Regular,...,No,No,NaN,No,Yes,2,Branch,NaN,Unsubscribed,No
507,FSL-0421,Nicole Roberts,827457336V,Female,1982-09-02,41,Ratnapura,Sabaragamuwa,Rural,Regular,...,No,Yes,404601.63,No,Yes,3,Referral,Family,Responded,No

The results point to the following concerns:
1. There seems to be no standardized format for "Gender", values include "Female", "Male", "M", "male", "FEMALE", "F", "MALE", "f."
2. The "District" column contains typos "Columbo", "Kanady", "Gale", "Jafna", these values have lead to duplicates in the number of categories.
3. The "Customer_ID" with is assumed to be the primary identifier is duplicated over 8 times, while 3 entire rows seem identical.
4. Same standardization issue occurs with "Account_Status" where values include "Active", "Inactive", "Suspended", "active", "INACTIVE", "suspended", "Active."
5. "District", "Customer_Segment", "Has_Loan" ("Has_Loan" was identified previously) has 5 missing values.

In [41]:
missing_val_cols=["Customer_ID", "District", "Customer_Segment", "Has_Loan"]

print(df.loc[df[["District", "Customer_Segment", "Has_Loan"]].isna().any(axis=1), missing_val_cols])

    Customer_ID     District Customer_Segment Has_Loan
28     FSL-0029      Colombo              NaN       No
50     FSL-0051          NaN          Regular       No
85     FSL-0086    Ratnapura          Regular      NaN
92     FSL-0093   Kurunegala              NaN       No
120    FSL-0121          NaN          Regular       No
165    FSL-0166      Colombo          Regular      NaN
168    FSL-0169  Trincomalee              NaN       No
225    FSL-0226      Colombo          Premium      NaN
230    FSL-0231          NaN          Regular      Yes
275    FSL-0276       Matara              NaN      Yes
355    FSL-0356      Colombo          Starter      NaN
370    FSL-0371          NaN          Regular      Yes
400    FSL-0401      Badulla              NaN      Yes
450    FSL-0451          NaN          Regular      Yes
475    FSL-0476      Badulla          Regular      NaN